// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Comment struct {
	ID        string `json:"_id"`
	Text      string `json:"text"`
	CommentBy *User  `json:"commentBy"`
	CommentOn *Post  `json:"commentOn"`
}

type FetchComment struct {
	ID string `json:"id"`
}

type FetchPost struct {
	ID string `json:"id"`
}

type FetchUser struct {
	ID string `json:"id"`
}

type NewComment struct {
	Text      string `json:"text"`
	CommentBy string `json:"commentBy"`
	CommentOn string `json:"commentOn"`
}

type NewPost struct {
	PostedBy    string  `json:"postedBy"`
	ImageURL    string  `json:"imageURL"`
	Description *string `json:"description,omitempty"`
	Likes       int     `json:"likes"`
}

type NewUser struct {
	Username       string  `json:"username"`
	Name           string  `json:"name"`
	About          *string `json:"about,omitempty"`
	Email          string  `json:"email"`
	AvatarImageURL string  `json:"avatarImageURL"`
	PublicWallet   string  `json:"publicWallet"`
	PrivateWallet  string  `json:"privateWallet"`
}

type Post struct {
	ID          string     `json:"_id"`
	PostedBy    *User      `json:"postedBy"`
	ImageURL    string     `json:"imageURL"`
	Description *string    `json:"description,omitempty"`
	Likes       int        `json:"likes"`
	Comments    []*Comment `json:"comments,omitempty"`
}

type User struct {
	ID             string  `json:"_id"`
	Username       string  `json:"username"`
	Name           string  `json:"name"`
	About          *string `json:"about,omitempty"`
	Email          string  `json:"email"`
	AvatarImageURL string  `json:"avatarImageURL"`
	Posts          []*Post `json:"posts,omitempty"`
	Following      []*User `json:"following,omitempty"`
	Followers      []*User `json:"followers,omitempty"`
	PublicWallet   string  `json:"publicWallet"`
	PrivateWallet  string  `json:"privateWallet"`
}

type Status string

const (
	StatusNotStarted Status = "NOT_STARTED"
	StatusInProgress Status = "IN_PROGRESS"
	StatusCompleted  Status = "COMPLETED"
)

var AllStatus = []Status{
	StatusNotStarted,
	StatusInProgress,
	StatusCompleted,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusNotStarted, StatusInProgress, StatusCompleted:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
